language: android
jdk: oraclejdk8
email: false

env:
  global:
   - ANDROID_API_LEVEL=27
   - EMULATOR_API_LEVEL=19
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3
   - ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    # Support library
    - extra-android-support
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-27"

before_script:
  #- cd Go4Lunch
  - chmod +x gradlew
  - ./gradlew build jacocoTestReport coveralls
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)